LIB := adxl345lib
SOURCES := $(LIB)/Adxl345.cpp $(LIB)/I2cBus.cpp $(LIB)/Logging.cpp $(LIB)/UsbBus.cpp $(LIB)/XYZCoordinate.cpp Oled.cpp OledCoordinateDisplay.cpp
HEADERS := $(LIB)/Adxl345.hpp $(LIB)/I2cBus.hpp $(LIB)/Logging.hpp $(LIB)/UsbBus.hpp $(LIB)/XYZCoordinate.hpp Oled.hpp OledCoordinateDisplay.hpp
SEARCH  := 
RELATIVE := ../..
include $(RELATIVE)/Makefile.due